# Generated by Django 5.1.2 on 2024-10-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_moviesname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='description',
            field=models.TextField(default='texto prueba', max_length=255),
            preserve_default=False,
        ),
    ]
