# Generated by Django 5.1.2 on 2024-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_name_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='image_url',
            field=models.CharField(default='link', max_length=255),
            preserve_default=False,
        ),
    ]
